"""Pipeline module for Idea Agent <-> Experiment Agent closed loop."""

from .experiment_to_symbolic import (
    convert_ablation_to_symbolic_memory,
    normalize_component_family,
)
from .survey_idea_handoff import (
    SURVEY_GAP_LEDGER_SCHEMA_VERSION,
    SURVEY_IDEA_HANDOFF_SCHEMA_VERSION,
    SURVEY_MANIFEST_SCHEMA_VERSION,
)
from .survey_gap_ledger import (
    build_deterministic_gap_ledger,
    build_initial_gap_ledger,
    build_survey_gap_ledger,
    extract_deterministic_gaps,
    load_evidence_plan,
    read_evidence_plan,
)
from .survey_gap_candidates import (
    GapCandidate,
    SectionAwarePaperInput,
    SURVEY_GAP_CANDIDATE_LEDGER_SCHEMA,
    SURVEY_GAP_CANDIDATE_LEDGER_SCHEMA_VERSION,
    SURVEY_GAP_CANDIDATE_SCHEMA_VERSION,
    build_gap_candidate_payload,
    build_gap_candidate_ledger_payload,
    build_paper_limitation_extraction_prompt,
    build_section_aware_paper_input,
    build_survey_gap_extraction_prompt,
    extract_gap_candidates,
    extract_paper_limitation_candidates,
    extract_survey_gap_candidates,
    validate_gap_candidate_payload,
    validate_gap_candidate_ledger_payload,
)
from .survey_gap_adjudication import (
    SURVEY_GAP_ADJUDICATION_SCHEMA,
    SURVEY_GAP_ADJUDICATION_SCHEMA_VERSION,
    SURVEY_GAP_COVERAGE_SCHEMA,
    SURVEY_GAP_COVERAGE_SCHEMA_VERSION,
    adjudicate_gap_candidates,
    build_coverage_matrix,
    build_gap_coverage_artifact,
    deduplicate_gap_candidates,
    detect_gap_contradictions,
    synthesize_cross_paper_gaps,
    validate_coverage_matrix_payload,
    validate_gap_adjudication_payload,
)
from .survey_gap_triage import (
    SURVEY_GAP_TRIAGE_SCHEMA_VERSION,
    TARGETED_VERIFICATION_TOP_K,
    build_gap_triage_artifact,
    triage_gap_records,
)
from .survey_handoff_projection import (
    build_survey_idea_handoff_projection,
    project_accepted_gaps_to_handoff,
)
from .survey_handoff_persistence import (
    SURVEY_MANIFEST_FILENAME,
    SurveyArtifactPublicationError,
    build_project_context_artifact,
    publish_survey_run_artifacts,
    sha256_file,
    verify_survey_manifest_artifacts,
)
from .survey_idea_loader import (
    SurveyIdeaContext,
    SurveyIdeaLoadError,
    load_survey_idea_context,
)

__all__ = [
    "convert_ablation_to_symbolic_memory",
    "normalize_component_family",
    "SURVEY_GAP_LEDGER_SCHEMA_VERSION",
    "SURVEY_IDEA_HANDOFF_SCHEMA_VERSION",
    "SURVEY_MANIFEST_SCHEMA_VERSION",
    "build_deterministic_gap_ledger",
    "build_initial_gap_ledger",
    "build_survey_gap_ledger",
    "extract_deterministic_gaps",
    "load_evidence_plan",
    "read_evidence_plan",
    "GapCandidate",
    "SectionAwarePaperInput",
    "SURVEY_GAP_CANDIDATE_LEDGER_SCHEMA_VERSION",
    "SURVEY_GAP_CANDIDATE_LEDGER_SCHEMA",
    "SURVEY_GAP_CANDIDATE_SCHEMA_VERSION",
    "build_gap_candidate_payload",
    "build_gap_candidate_ledger_payload",
    "build_paper_limitation_extraction_prompt",
    "build_section_aware_paper_input",
    "build_survey_gap_extraction_prompt",
    "extract_gap_candidates",
    "extract_paper_limitation_candidates",
    "extract_survey_gap_candidates",
    "validate_gap_candidate_payload",
    "validate_gap_candidate_ledger_payload",
    "SURVEY_GAP_ADJUDICATION_SCHEMA_VERSION",
    "SURVEY_GAP_ADJUDICATION_SCHEMA",
    "SURVEY_GAP_COVERAGE_SCHEMA",
    "SURVEY_GAP_COVERAGE_SCHEMA_VERSION",
    "adjudicate_gap_candidates",
    "build_coverage_matrix",
    "build_gap_coverage_artifact",
    "deduplicate_gap_candidates",
    "detect_gap_contradictions",
    "synthesize_cross_paper_gaps",
    "validate_coverage_matrix_payload",
    "validate_gap_adjudication_payload",
    "SURVEY_GAP_TRIAGE_SCHEMA_VERSION",
    "TARGETED_VERIFICATION_TOP_K",
    "build_gap_triage_artifact",
    "triage_gap_records",
    "build_survey_idea_handoff_projection",
    "project_accepted_gaps_to_handoff",
    "SURVEY_MANIFEST_FILENAME",
    "SurveyArtifactPublicationError",
    "build_project_context_artifact",
    "publish_survey_run_artifacts",
    "sha256_file",
    "verify_survey_manifest_artifacts",
    "SurveyIdeaContext",
    "SurveyIdeaLoadError",
    "load_survey_idea_context",
]
