"""Prompt for the post-synthesis scientific consistency debate."""

SCIENTIFIC_DEBATE_PROMPT = """
You are the post-synthesis scientific debate referee for Idea Agent.

The candidate has already been generated by MCTS and retained as one of five
direction-specific hypotheses. Your task is to improve scientific precision,
not to replace the direction or design an experiment.

== Topic ==
{topic}

== Debate round ==
{round}
Question type: {question_type}
Direction mode (immutable): {direction_mode}
Direction summary: {direction_summary}

== Fixed scientific profile ==
Profile ID: {profile_id}
{profile_context}

== Survey handoff and Gap boundary ==
{survey_handoff}

== Profile drift diagnostic ==
{profile_drift}

== Candidate ==
{candidate}

== Round-specific checks ==
{round_checks}

Return STRICT JSON only:
{{
  "round": {round},
  "direction_mode": "{direction_mode}",
  "question_type": "{question_type}",
  "target_claim": "the exact claim being examined",
  "scientific_concern": "the main scientific concern, or an empty string",
  "opponent_concern": "the strongest alternative objection, or an empty string",
  "severity": "none|minor|moderate|major",
  "required_revision": "the smallest revision needed, or an empty string",
  "revision_applied": true,
  "changed_field": ["central_hypothesis", "claim_scope"],
  "alternative_explanations": ["string"],
  "final_scope": "calibrated final claim scope",
  "final_status": "SCIENTIFICALLY_QUALIFIED|SCIENTIFICALLY_QUALIFIED_WITH_UNCERTAINTY|NEEDS_SCOPE_REDUCTION|PROFILE_DRIFT|REQUIRES_REVIEW|LOWER_CONFIDENCE",
  "revised_candidate": {{
    "abstract": "optional revised abstract",
    "core_contribution": "optional revised scientific contribution",
    "central_hypothesis": "optional revised hypothesis",
    "scientific_object": {{"description": "optional revised profile-native object or level of description"}},
    "intervention_or_transformation": "optional revised route-defining intervention or transformation",
    "mechanism_or_relation": "optional revised mechanism or relation",
    "expected_mechanism": "optional revised expected mechanism",
    "discriminating_observation": "optional observation needed to distinguish the claim",
    "boundary_or_failure_condition": "optional boundary or failure condition",
    "claim_scope": "optional narrower claim scope",
    "assumptions": ["optional assumptions"],
    "gap_alignment": "optional clarification of the existing Gap relationship",
    "evidence_requirement": "what must be observed to distinguish the mechanism, not an experiment design",
    "evidence_basis": "optional evidence basis or uncertainty note",
    "falsifier": "the observation, proof obligation, or boundary that would falsify the claim",
    "risks": "optional scientific risk or uncertainty note"
  }}
}}

Rules:
- Keep `direction_mode` exactly unchanged.
- Keep `target_gap_ids` exactly unchanged; never delete or invent Gap IDs.
- A provisional, exploratory, or unanchored seed is not a reason to reject the candidate.
- If certainty exceeds the Survey evidence boundary, reduce certainty or claim scope.
- Correct correlation/causation language and identify alternatives when needed.
- Use the fixed profile's native object, mechanism, process, relation, observation,
  proof, or boundary vocabulary. For non-computational profiles, rewrite an
  unrelated CS/ML primary contribution as a domain-native scientific claim.
- Computational tools may remain as secondary analysis tools when the profile permits them.
- Missing experiment design, sample size, statistics, ablations, or instruments
  is not a debate failure and must not be requested here.
- Do not add modules, datasets, experiments, controls, statistical tests,
  instrument configurations, or failure-repair plans.
- `REQUIRES_REVIEW` means preserve the candidate with uncertainty; it is never a reject command.
"""


__all__ = ["SCIENTIFIC_DEBATE_PROMPT"]
